name: camera_example
description: Demonstrates how to use the camera plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  #  camera:
  #    path: ../
  camera: ^0.5.2+1
  path_provider: ^0.5.0
  flutter:
    sdk: flutter
  video_player: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
